apiVersion: v1
kind: Service
metadata:
     name: order-management-svc
     labels:
          app: order-management-app
          tier: backend
spec:
     ports:
          - port: 7012
            targetPort: 8080
     type: ClusterIP
     selector:
          app: order-management-app
          tier: backend